### ISSUE TITLE
Add openode addons schema description

### ISSUE THREAD

**Issue by d1soft** [openode-io/addons#1]
What about addons schema description?

I looked at examples, and how i can see, openode's addons json-schema is simplified and unified configuration, that be used to generate instances build configurations with the use openode's features?

Then ```minimum_memory_mb``` config is minimal required openode instance tier? And ```requires_persistence``` and ``` persistent_path``` it is configs referenced to [Persistence storage](https://www.openode.io/docs/platform/persistence.md)?

I look forward to detailed docs, that will be helpful to develop openode's addons ecosystem. Thanks :)

**Comment by martinlevesque** [comment]
@d1soft good point, will look at adding some documentation about the schema.

Basically those addons configurations are used to deploy extra services and attach them automatically to your instance. They can be configured from Settings, section Addons.

`Then minimum_memory_mb config is minimal required openode instance tier?
`

It's the minimum memory required for the addon itself.

`And requires_persistence and persistent_path it is configs referenced to Persistence storage?`

The addon persistence settings are for the addon only. This documentation https://www.openode.io/docs/platform/persistence.md is for the instance itself only, not the addon.

We need to add some documentation about the addons also.

**Comment by martinlevesque** [comment]
@d1soft  Just added a first version here: https://github.com/openode-io/addons 

Let us know if it looks clear.
