### ISSUE TITLE
Addon with jaeger tracing all in one container for collecting logs

### ISSUE THREAD

**Issue by petranb2** [openode-io/addons#10]
Jaeger is a cloud native app for collecting and querying logs. 
I suggest to create an addon with [jaegertracing/all-in-one](https://hub.docker.com/r/jaegertracing/all-in-one ) container.
Jaeger offers web UI

**Comment by martinlevesque** [comment]
client for testing https://github.com/jaegertracing/jaeger-client-node

**Comment by martinlevesque** [comment]
@petranb2 hey, jaeger requires a storage mechanism, and so the proper ENV variables should be passed, https://www.jaegertracing.io/docs/1.6/deployment/

Requires some research on what ENV variables should be possible to pass in the addon.

**Comment by petranb2** [comment]
@martinlevesque [jaegertracing/all-in-one](https://www.jaegertracing.io/docs/1.6/getting-started/#all-in-one-docker-image) uses memory storage and it's for development purposes.
I will search for storage mechanisms and further details for a production deploy

**Comment by petranb2** [comment]
@martinlevesque  I think the solution with a database as a local storage is the best for our case [link](https://www.jaegertracing.io/docs/1.21/deployment/#badger---local-storage
). 
With this case we can use the all in one container add a volume and have a permanent database.
```bash
docker run \
  -e SPAN_STORAGE_TYPE=badger \
  -e BADGER_EPHEMERAL=false \
  -e BADGER_DIRECTORY_VALUE=/badger/data \
  -e BADGER_DIRECTORY_KEY=/badger/key \
  -v <storage_dir_on_host>:/badger \
  -p 16686:16686 \
  jaegertracing/all-in-one:1.21
```
Cassandra and elastic search will need containers with at least 2gb of memory

**Comment by martinlevesque** [comment]
@petranb2 thanks. So in this example it basically needs a permanent disk in **/badger** and port 16686 is HTTP based?

If you have a client already to test it could you please post it here.

**Comment by petranb2** [comment]
@martinlevesque The port 16686 is for the UI only. We have to add the ports to collect the logs :
```bash
docker run -d --name jaeger -p 6831:6831/udp -p 6832:6832/udp -p 5778:5778 -p 16686:16686 -p 14268:14268 -p 14250:14250 jaegertracing/all-in-one:1.21
```

**Comment by petranb2** [comment]
With this example you can send logs [examples](https://github.com/yurishkuro/opentracing-tutorial/tree/master/nodejs)
[lesson-1](https://github.com/yurishkuro/opentracing-tutorial/tree/master/nodejs/lesson01)

**Comment by petranb2** [comment]
@martinlevesque I made a sample app with express and the jaeger-client as a middleware. The middleware send spans for every route at the start and the end of a request and binds the loggers at `req.span` to be accessibly from the router.
  https://github.com/petranb2/jaeger-express

**Comment by martinlevesque** [comment]
thanks, will look at it as soon as possible

**Comment by martinlevesque** [comment]
Hey,

Just added a first version as jaeger-collector.

The UI don't seem work well however by adding an http endpoint (as the assets refer to the root path and not relative one), by adding an addon HTTP endpoint on port 16686.
