### ISSUE TITLE
Separated services versions

### ISSUE THREAD

**Issue by d1soft** [openode-io/addons#4]
What about different LTS or wide spreaded versions of same service? 
For example, MySQL 8.0.* and MySQL 5.7. 

I think it would be nice to add a specification for such cases.

For example, add new field to config with allowed range:
```
versions: ['8.0', '5.6']
```
Is it even possible to do it in future?

**Comment by martinlevesque** [comment]
that's a good point. I would think it should be based on the tags https://hub.docker.com/_/mysql?tab=tags&page=1&ordering=last_updated

depending on the tag you select it would use the proper image tag, example: mysql:the-tag-version

**Comment by d1soft** [comment]
@martinlevesque hm, can do this via different config files?

- /database
-- /mysql-8.0
-- /mysql-5.7

Like that?

**Comment by martinlevesque** [comment]
Hey @d1soft 

There is no need to have different config files if the **image** and ENV variables are the same. Instead the user will be able to pick an image **tag** available by the image. And so there is no change to do in this repository (addons). 

Created tasks in other repositories:

- https://github.com/openode-io/openode-api/issues/481
- https://github.com/openode-io/openode-www/issues/264

**Comment by d1soft** [comment]
@martinlevesque i see, thx, close then.
