### ISSUE TITLE
Naming conventions for categories

### ISSUE THREAD

**Issue by d1soft** [openode-io/addons#6]
It's be helpful have list with names of categories, includes categories that not added yet. I think some lines in readme be enough. 

And one more about topic. I want add RabbitMQ. Which category name i can use: 'message-broker', 'message-queue' or any another specified?

**Comment by martinlevesque** [comment]
Good point.

For RabbitMQ category I think message-broker would be a good fit.

**Comment by martinlevesque** [comment]
added a description
